# Funding

# This project is maintained by Kancelaria Adwokacka Adwokat Katarzyna Maj
# For business inquiries or sponsorship opportunities, please contact:

# custom: ["https://www.adwokat-trzebnica.com"]

# GitHub Sponsors
# github: []

# Open Collective
# open_collective: []

# Patreon
# patreon: []

# Ko-fi
# ko_fi: []

# Contact for funding inquiries
custom: ["mailto:biuro@adwokat-trzebnica.com"]
