labels: [discussion]
body:
  - type: markdown
    attributes:
      value: |
        ## General Discussion
        Start a conversation about the law office website project.
  
  - type: textarea
    id: topic
    attributes:
      label: Discussion Topic
      description: What would you like to discuss?
    validations:
      required: true
